// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqATQ1TRHhDBe3UjOUk45UeuIQ57S_9Jg',
    appId: '1:34131151696:web:434e41ce8a75c103e5ba55',
    messagingSenderId: '34131151696',
    projectId: 'mynotes-7eb1d',
    authDomain: 'mynotes-7eb1d.firebaseapp.com',
    storageBucket: 'mynotes-7eb1d.appspot.com',
    measurementId: 'G-CFZ4Z45W01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQrcUrjWf9bEoWFZG0nU6FWSIElFFFeko',
    appId: '1:34131151696:android:a90bf24483a8ba2fe5ba55',
    messagingSenderId: '34131151696',
    projectId: 'mynotes-7eb1d',
    storageBucket: 'mynotes-7eb1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwyx-gMfdop80NALIGNvfR7anBI-_8th4',
    appId: '1:34131151696:ios:cc5cad08cfcd03b7e5ba55',
    messagingSenderId: '34131151696',
    projectId: 'mynotes-7eb1d',
    storageBucket: 'mynotes-7eb1d.appspot.com',
    iosClientId: '34131151696-kbtbh2qgrqpj4unsvvgtv5a358vke9nn.apps.googleusercontent.com',
    iosBundleId: 'com.innovationlabs.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwyx-gMfdop80NALIGNvfR7anBI-_8th4',
    appId: '1:34131151696:ios:758fd590cdcf2d91e5ba55',
    messagingSenderId: '34131151696',
    projectId: 'mynotes-7eb1d',
    storageBucket: 'mynotes-7eb1d.appspot.com',
    iosClientId: '34131151696-85h03qnudehr50jji34erikiai75erm2.apps.googleusercontent.com',
    iosBundleId: 'com.innovationlabs.mynotes.RunnerTests',
  );
}
